blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/your-org/your-repo/discussions
    about: Ask general questions or propose ideas informally here.
